sierramlapp/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from sierramlapp.users.forms import LoginForm

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')

@main.route('/about')
def about():
    return render_template('about.html', title='About')

sierramlapp/mlapp/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app, send_from_directory
import os
import pandas as pd
from sierramlapp.mlapp.forms import PricePrediction
from sierramlapp.mlapp.utils import save_file, printHttpError, saveBlobToFile, processResults, uploadFileToBlob, invokeBatchExecutionService

mlapp = Blueprint('mlapp', __name__)

@mlapp.route('/mlhome',methods=['GET','POST'])
def mlhome():
    form = PricePrediction()
    if form.validate_on_submit():
        if form.excel.data:
            global excel_filename
            excel_filename = form.excel.data.filename
            df = pd.read_csv(form.excel.data)
            save_file(form.excel.data)
            global excel_df
            excel_df = df
            dict = df.to_dict(orient='records')
            return render_template('mlhome.html',title='Price Prediction', form=form, dict=dict, len=len, col_names= df.columns)
    return render_template('mlhome.html', title='Price Prediction', form=form)

@mlapp.route('/predict')
def predict():
    form = PricePrediction()
    result_download_link = invokeBatchExecutionService(excel_filename)
    form.excel.data = os.path.join(current_app.root_path, 'static/data_files/predicted_result.csv')
    df = pd.read_csv(form.excel.data)
    dict = df.to_dict(orient='records')
    return render_template('mlhome.html', title='Price Prediction', form=form, dict=dict, len=len, col_names= df.columns, result_download_link=result_download_link)

sierramlapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sierramlapp import db, bcrypt
from sierramlapp.models import User
from sierramlapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm,RequestPasswordResetForm, ResetPasswordForm
from sierramlapp.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You are now able to login..!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Failed. Please check your credentials..!', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts= posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestPasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_password_reset_token(token)
    if user is None:
        flash('Thats an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You are now able to login..!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset Password', form=form)

sierramlapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

sierramlapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email  }}</p>
        </div>
      </div>
        <form class="" action="" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sierramlapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1>Welcome to Sierra Prediction Tool..</h1>
        {% if current_user.is_authenticated %}
            <a class="btn btn-primary m-2" href="{{ url_for('mlapp.mlhome') }}">Lets go for prediction</a>
        {% endif %}

    </div>
{% endblock content %}

sierramlapp/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
    {% if title %}
        <title>Flask Blog - {{ title }}</title >
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container" style="margin-left: 0px; margin-right: 0px;max-width: 1523px;">
          <a class="navbar-brand mr-4" href="/home">Sierra Predictor</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      <div class="alert alert-{{ category }}">
                        {{ message }}
                      </div>
                  {% endfor%}
              {% endif%}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    {% block script %} {% endblock %}
  </body>
</html>

sierramlapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
      <form class="form-signin card" action="" method="post" style="margin-top: 50px;">
          {{ form.hidden_tag() }}
          <fieldset class="form-group card-body" style="padding:0.25rem;">
              <div class="text-center mb-4">
                  <img class="mb-2" src="{{ url_for('static', filename='logo.png') }}" alt="" width="72" height="72">
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-check mb-3">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}
              </div>
              <div class="form-group">
                  {{ form.submit(class="btn btn-sm btn-primary btn-block") }}
                  <small class="text-muted">
                      <a href="{{ url_for('users.reset_request') }}">Forgot Password? </a>
                  </small>
              </div>
          </fieldset>

      </form>
    <div class="border-top pt3 form-signin">
      <small class="text-muted">
          Need An Account? <a class="ml-2" href=" {{ url_for('users.register') }}">Sign Up Now</a>
      </small>
    </div>
{% endblock content %}

sierramlapp/templates/mlhome.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form class="" action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
              <legend class="border-bottom mb-4">Predict Price</legend>
              <div class="form-group col-md-8" style="float:left;">
                  {{ form.excel.label() }}
                  {{ form.excel(class="form-control-file") }}
                  {% if form.excel.errors %}
                      {% for error in form.excel.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                      {% endfor %}
                  {% endif %}
              </div>
              <div class="form-group col-md-4 text-right pt-3" style="float:right;">
                    {{ form.submit(class="btn btn-outline-info") }}
              </div>
          </fieldset>

      </form>
      {% if form.excel.data %}
      <div class="card">
        <div class="card-body">
        <legend class="border-bottom mb-4">Table Name Comes here
          {% if result_download_link %}
              <a class="btn btn-outline-primary btn-sm float-right ml-2" href="{{ result_download_link }}"> Download</a>
          {% endif %}
              <a class="btn btn-outline-primary btn-sm float-right" href="{{ url_for('mlapp.predict') }}"> Predict Data</a>
        </legend>
        <table id="myTable" class="display table responsive" width=100%>
            <thead>
                <tr>
                    {% for col in col_names %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
              {% for i in dict %}
              <tr>
                {% for x in i %}
                    <td> {{ i[x] }}</td>
                {% endfor %}
              </tr>
              {% endfor %}

            </tbody>
        </table>
      </div>
    </div>
      {% endif %}
     </div>
{% endblock content %}

{%  block script %}
<script type="text/javascript">
  $(document).ready(function(){
      $('#myTable').DataTable({
        scrollY:        '50vh',
        scrollCollapse: true,
        scrollX: true
      });

      $('input[type="search"]').addClass("form-group")
  })
</script>
{% endblock %}

sierramlapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form class="" action="" method="post">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Join Today</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
                  {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.confirm_password.label(class="form-control-label") }}
                  {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
    </div>
    <div class="border-top pt3">
      <small class="text-muted">
          Already Have An Account? <a class="ml-2" href=" {{ url_for('users.login') }}">Sign In</a>
      </small>
    </div>
{% endblock content %}

sierramlapp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form class="" action="" method="post">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Reset Password</legend>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
    </div>
{% endblock content %}

sierramlapp/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form class="" action="" method="post">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Reset Password</legend>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.confirm_password.label(class="form-control-label") }}
                  {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                      {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
    </div>
{% endblock content %}